// flow-typed signature: 080baa100a7fa0b22ecb9327bb13d044
// flow-typed version: <<STUB>>/open_v^6.2.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'open/index' {
  declare module.exports: $Exports<'open'>;
}
declare module 'open/index.js' {
  declare module.exports: $Exports<'open'>;
}
