// flow-typed signature: aebd4426631adcc3831ee426614e8289
// flow-typed version: <<STUB>>/require-glob_v^3.2.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-glob/src/require-glob' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/deep/a/a1' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/deep/a/a2' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/deep/b/b_b-b/_b.b1' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/deep/b/b_b-b/b.b2' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/deep/b/b1' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/deep/b/b2' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/random' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/shallow/a' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/shallow/b' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/shallow/c' {
  declare module.exports: any;
}

declare module 'require-glob/test/fixtures/shallow/d' {
  declare module.exports: any;
}

declare module 'require-glob/test/require-glob' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-glob/src/require-glob.js' {
  declare module.exports: $Exports<'require-glob/src/require-glob'>;
}
declare module 'require-glob/test/fixtures/deep/a/a1.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/deep/a/a1'>;
}
declare module 'require-glob/test/fixtures/deep/a/a2.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/deep/a/a2'>;
}
declare module 'require-glob/test/fixtures/deep/b/b_b-b/_b.b1.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/deep/b/b_b-b/_b.b1'>;
}
declare module 'require-glob/test/fixtures/deep/b/b_b-b/b.b2.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/deep/b/b_b-b/b.b2'>;
}
declare module 'require-glob/test/fixtures/deep/b/b1.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/deep/b/b1'>;
}
declare module 'require-glob/test/fixtures/deep/b/b2.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/deep/b/b2'>;
}
declare module 'require-glob/test/fixtures/random.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/random'>;
}
declare module 'require-glob/test/fixtures/shallow/a.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/shallow/a'>;
}
declare module 'require-glob/test/fixtures/shallow/b.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/shallow/b'>;
}
declare module 'require-glob/test/fixtures/shallow/c.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/shallow/c'>;
}
declare module 'require-glob/test/fixtures/shallow/d.js' {
  declare module.exports: $Exports<'require-glob/test/fixtures/shallow/d'>;
}
declare module 'require-glob/test/require-glob.js' {
  declare module.exports: $Exports<'require-glob/test/require-glob'>;
}
