// flow-typed signature: f6e1e1c87c1339a2c71aedc1d3eaf3b4
// flow-typed version: <<STUB>>/smart-restart_v^2.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smart-restart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smart-restart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smart-restart/launcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smart-restart/index' {
  declare module.exports: $Exports<'smart-restart'>;
}
declare module 'smart-restart/index.js' {
  declare module.exports: $Exports<'smart-restart'>;
}
declare module 'smart-restart/launcher.js' {
  declare module.exports: $Exports<'smart-restart/launcher'>;
}
